---
# defaults file for docker
docker_obsolete_packages:
  - docker.io
  - docker-compose
  - docker-doc
  - podman-docker
  - containerd
  - runc

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_packages_state: present

# Enable repo setup
docker_add_repo: true

docker_repo_url: https://download.docker.com/linux

docker_apt_release_channel: stable
docker_apt_arch: amd64

docker_apt_repository: "deb [arch={{ docker_apt_arch }} signed-by=/etc/apt/keyrings/docker.asc] {{ docker_repo_url }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"

docker_apt_gpg_key: "{{ docker_repo_url | lower }}/{{ ansible_distribution | lower }}/gpg"

docker_apt_filename: "docker"

# docker service options
docker_service_manage: true
docker_service_enabled: true
docker_restart_handler_state: "restarted"