apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "conductor.fullName" . }}-api
data:
{{/* Data from values.yml 
  {{- tpl (toYaml .Values.conductorServer.config) . | nindent 2 }}

  {{- range $key, $value := .Values.conductorServer.data }}
  {{ $key }}: {{ tpl $value $ | quote | indent 2 }}
  {{- end }}

*/}}

  {{/* $ in tpl context points to root, but . will point within loop */}}
  {{- range $key, $value := .Values.conductorServer.config }}
  {{ $key }}: {{ tpl ( toString $value) $ | quote }}
  {{- end }}