
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "vm1"
  config.vm.network "private_network", ip: "192.168.56.10"
  
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = "2"
    vb.name = "vm1"
  end

  config.vm.provision "file", source: "~/.ssh/vagrant-key.pub", destination: "~/.ssh/vagrant-key.pub"

  config.vm.provision "shell", inline: <<-EOF
    cat /home/vagrant/.ssh/vagrant-key.pub >> /home/vagrant/.ssh/authorized_keys
  EOF

end
