Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "tanveer-workstation"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.56.1"
  config.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.username = "vagrant"
  # config.ssh.password = "ubuntu"
  config.ssh.private_key_path=["~/.vagrant.d/insecure_private_key"]
  config.ssh.insert_key = false
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
    vb.cpus = "2"
    vb.name = "tanveer-workstation"
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
  SHELL
end