---
- name: "Install dependencies"
  apt:
    name: apt-transport-https
    state: present

- name: "Add the helm key"
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

- name: "Add the helm repository"
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present

- name: "Install helm"
  apt:
    name: helm
    state: present
    update_cache: yes
    