namespace: conductor

conductorServer:
  replicaCount: 1
  image:
    repository: conductor 
    tag: server
  serverPort: 8080
  serverNodePort: 30080
  uiPort: 5000
  uiNodePort: 30050 
  
  conifg:
    spring.datasource.url: "jdbc:postgresql://{{ include 'conductor.fullName' . }}-postgres:5432/postgres"

postgres:
  replicaCount: 1
  image:
    repository: postgres
    # tag: 6.2.3-alpine
  port: 5432
  nodePort: 30432