namespace: conductor

conductorServer:
  replicaCount: 1
  image:
    repository: conductor 
    tag: server
  serverPort: 8080
  serverNodePort: 30080
  uiPort: 5000
  uiNodePort: 30050 


  data:
    three: 3
    two: "2"
    one: "1"

  config:
    # {{- /* DB */}}
    conductor.db.type: "postgres"
    conductor.queue.type: "postgres"
    # conductor.external-payload-storage.type: "postgres"
    spring.datasource.url: "jdbc:postgresql://{{ include \"conductor.fullName\" . }}-postgres:5432/postgres"

    # {{- /* DB Connectivity */}}
    spring.datasource.username: "conductor"
    spring.datasource.password: "conductor"

    # {{- /* Indexing Properties */}}
    conductor.indexing.enabled: true
    conductor.indexing.type: "postgres"
    # {{- /* Required to disable connecting to elasticsearch. */}}
    conductor.elasticsearch.version: 0

    # {{- /* Additional modules for metrics collection exposed to Prometheus (optional) */}}
    conductor.metrics-prometheus.enabled: "true"
    management.endpoints.web.exposure.include: "prometheus"

postgres:
  replicaCount: 1
  image:
    repository: postgres
    # tag: 6.2.3-alpine
  port: 5432
  nodePort: 30432