apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-node-exporter-service
  name: prometheus-node-exporter-service
  namespace: monitoring
spec:
  ports:
  - name: node-exporter
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app.kubernetes.io/instance: prometheus-node-exporter
    app.kubernetes.io/name: prometheus-node-exporter
  type: NodePort
