---
- name: Install packages
  hosts: localhost
  gather_facts: yes
  connection: local
  tasks:

    # - name: "apt clean"
    #   ansible.builtin.apt:
    #     clean: yes
    # - name: wait for apt lock
    #   shell: while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;
    #   become: yes

    - name: "update apt cache i.e sudo apt update"
      ansible.builtin.apt:
        update_cache: yes
      become: yes
      tags:
        - apt

    - name: "Installing apt packages"
      ansible.builtin.apt:
        name: 
          - tree
        state: present
      become: yes

    - name: "Removing apt packages"
      apt:
        name:
          - sysfsutils
        state: absent
      become: yes

    - name: "installing stow"
      ansible.builtin.apt:
        name: stow
        state: present
      become: yes

    - name: "installing xclip"
      apt:
        name: xclip
        state: absent
      become: yes

    - name: "installing xsel"
      apt:
        name: xsel
        state: present
      become: yes

    - name: "install bat"
      apt:
        name: bat
        state: present
      become: yes

        #    - name: "Install bitwarden"
        #      apt:
        #        deb: "https://vault.bitwarden.com/download/?app=desktop&platform=linux&variant=deb"
        #      become: yes

    - name: "Set flatpack remote url"
      flatpak_remote:
        name: flathub
        state: present
        enabled: true
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
          #    register: flatpak_remote_url_result
      tags:
        - flatpak

    - name: "Install wezterm with flatpak"
      community.general.flatpak:
        name: org.wezfurlong.wezterm
        remote: flathub
        state: absent
      become: yes
      tags:
        - flatpak

    - name: "install virtualbox, vagrant"
      ansible.builtin.apt:
        pkg:
          # - virtualbox ## installed manually using .deb
          # - virtualbox-dkms
          # - linux-headers-generic
          - vagrant
        state: present
      become: yes

    - name: "check virtualbox installation"
      command: vboxmanage --version

    - name: "check vagrant installation"
      command: vagrant --version

    - name: "check node --version"
      command: node --version
      register: node_version
      tags:
        - npm

    - name: "node version"
      debug:
        msg: "Current node version: {{ node_version.stdout }}" 
      tags:
        - npm

    - name: "Install tldr"
      community.general.npm:
        name: tldr
        global: true
        state: present
        when: node_version.stdout == "v20.13.1"
      tags:
        - npm

    - name: "Create a directory for vim plug"
      file:
        path: ~/.vim/autoload
        state: directory
        mode: '0755'
      tags:
        - vim

    - name: "Download vim plug"
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: ~/.vim/autoload/plug.vim
        mode: '0644' 
      tags:
        - vim

          #- name: "Install amdgpu"
          #  apt:
          #    deb: "https://repo.radeon.com/amdgpu-install/6.1.3/ubuntu/focal/amdgpu-install_6.1.60103-1_all.deb"
          #  become: yes
          #  tags:
          #    - amdgpu

          #- name: "Install amggpu driver"
          #  command:  amdgpu-install -y --usecase=graphics
          #  become: yes
          #  tags:
          #    - amdgpu 
