---
- name: Install packages
  hosts: localhost
  gather_facts: yes
  connection: local
  tasks:
    - name: "Installing apt packages"
      ansible.builtin.include_tasks: tasks/apt.yml

    - name: "Installing flatpak packages"
      ansible.builtin.include_tasks: 
        file: tasks/flatpak.yml

    - name: "Installing npm packages"
      ansible.builtin.include_tasks:
        file: tasks/npm.yml

    - name: "Configuring vim"
      ansible.builtin.include_tasks:
        file: tasks/vim.yml