service: lambda-container

provider:
  name: aws
  runtime: python3.9
  region: ap-south-1
  memorySize: 128
  deploymentBucket:
    name: ${env:AWS_DEPLOYMENT_S3}
  role: ${env:AWS_LAMBDA_ROLE}
  # vpc:
  #   securityGroupIds:
  #     - ${env:AWS_SG1}
  #   subnetIds:
  #     - ${env:AWS_SUBNET1}
  # rest api config
  
functions:
  lambdaContainer:
    name: lambda-container-${opt:stage}
    image:
      uri: ${env:AWS_ACCOUNT_ID}.dkr.ecr.ap-south-1.amazonaws.com/lambda-container:latest
      # skipCacheInvalidation: true
