# - name: "apt clean"
    #   ansible.builtin.apt:
    #     clean: yes
    # - name: wait for apt lock
    #   shell: while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;
    #   become: yes

- name: "update apt cache i.e sudo apt update"
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: "Installing apt packages"
  ansible.builtin.apt:
    name: 
      - tree
      - tmux
      # - "gir1.2-gtop-2.0"
      # - "gir1.2-clutter-1.0"
      - stow
        #- rclone
      - xclip
      - bat
      # - vagrant
      # - flameshot
      # - pcscd
      # - libfuse2t64
        #- conky-all
      # - traceroute
      #- ifstat
        #- i3
    state: present
  become: yes

    #- name: "rclone version"
    #command: rclone --version

# - name: "Removing apt packages"
#   apt:
#     name:
#       - sysfsutils
#       - syncthing
#       - xsel
#       - rclone
#       - conky-all
#       - i3
#       - ifstat
#     state: absent
#   become: yes

#    - name: "Install bitwarden"
#      apt:
#        deb: "https://vault.bitwarden.com/download/?app=desktop&platform=linux&variant=deb"
#      become: yes

# - name: "check virtualbox installation"
#   command: vboxmanage --version

# - name: "check vagrant installation"
#   command: vagrant --version

#- name: "Install amdgpu"
#  apt:
#    deb: "https://repo.radeon.com/amdgpu-install/6.1.3/ubuntu/focal/amdgpu-install_6.1.60103-1_all.deb"
#  become: yes
#  tags:
#    - amdgpu

#- name: "Install amggpu driver"
#  command:  amdgpu-install -y --usecase=graphics
#  become: yes
#  tags:
#    - amdgpu 
